"""empty message

Revision ID: 5a12efd5a1e5
Revises: a54a867730d0
Create Date: 2016-07-21 21:22:48.268218

"""

# revision identifiers, used by Alembic.
revision = '5a12efd5a1e5'
down_revision = 'a54a867730d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    ### end Alembic commands ###
